# Generated by Django 2.1.5 on 2019-02-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subrace', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('special', models.CharField(blank=True, max_length=5000, null=True)),
                ('note', models.CharField(blank=True, max_length=5000, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('sound', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterRace',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('features', models.CharField(blank=True, max_length=5000, null=True)),
                ('traits', models.CharField(blank=True, max_length=5000, null=True)),
                ('weaknesses', models.CharField(blank=True, max_length=5000, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monster_race', to='monsters.MonsterRace'),
        ),
    ]
